### PR TITLE
Add code coverage report

### LINKED ISSUE #2834: setup code-coverage
setup a bot that reports code-coverage on PRs. I think https://about.codecov.io/ looks good (free for open source), but feel free to analyze. Maybe we need Tanner for installing the github app (in case of codecov: https://github.com/apps/codecov)

Ideally, I would like to see a failing pipeline if code coverage _decreases_ with a PR, because it means that something has been added / changed that is not covered by tests (which would be a requirement for PRs)

### PR DESCRIPTION
**Pull request by prateek3255**
Fixes #2834

### CODE REVIEW

**Comment by prateek3255** [comment]
@TkDodo You would need to [set up codecov](https://about.codecov.io/sign-up/) for this repo and install [this app](https://github.com/apps/codecov) bot comments for the status checks to work.

Also, I have set the target coverage to 90% with a 1% threshold, but there are a variety of recommended recipes that you can choose from from [here](https://docs.codecov.com/docs/common-recipe-list)

**Comment by TkDodo** [comment]
@prateek3255 thanks a lot - I can see that the bot _has_ posted already without installing the app 🤔 

https://github.com/tannerlinsley/react-query/pull/2894#issuecomment-962457825

**Comment by prateek3255** [comment]
> @prateek3255 thanks a lot - I can see that the bot _has_ posted already without installing the app 🤔
> 
> [#2894 (comment)](https://github.com/tannerlinsley/react-query/pull/2894#issuecomment-962457825)

Yeah, I am not really sure how it worked without installing 😅. Could it be possible that the app was already installed?

**Comment by TkDodo** [comment]
> Yeah, I am not really sure how it worked without installing 😅. Could it be possible that the app was already installed?

possibly. I'll ask @tannerlinsley . Anyways, this is great, thank you 🙏

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
