### PR TITLE
fix(persist): introduce in-house synchronous Storage interface

### PR DESCRIPTION
**Pull request by todorone**
### Rationale
Currently RQ has `createWebStoragePersistor` and `createAsyncStoragePersistor` which assumes that non-web platforms can have async storages only, which is not true. React Native has performant synchronous MMKV adapters support, which can't be used with RQ 3 right now directly because of interface incompatibility and `window` check(already fixed in v4).
Related discussion: https://github.com/tannerlinsley/react-query/discussions/3667

### Changes
Introduce own `Storage` interface to make possible using `createWebStoragePersistor` in React Native without TS errors.

### CODE REVIEW

**Comment by TkDodo** [comment]
thanks. can you make a PR towards the `beta` branch ?

**Comment by todorone** [comment]
> thanks. can you make a PR towards the `beta` branch ?

Oops, missed this point, sorry.
Is it ok now?

**Comment by TkDodo** [comment]
there are conflicts now because we've renamed the directory - in v4, the plugin is no longer experimental

**Comment by todorone** [comment]
> there are conflicts now because we've renamed the directory - in v4, the plugin is no longer experimental

sorry for a mess, created new "clean" PR

**Pull request closed without merging**
