### PR TITLE
feat: add useIsMutating hook

### PR DESCRIPTION
**Pull request by benediktviebahn**
This PR adds a useIsMutating hook as discussed in #1298.

Let me know if it needs any changes.

### CODE REVIEW

**Comment by benediktviebahn** [comment]
Any idea why the tests are failing? I saw some lint errors in VS Code but I assumed I had something incorrectly set up.

**Comment by TkDodo** [comment]
looks like a cyclic import:

```
/home/runner/work/react-query/react-query/src/core/retryer.ts
Error:   1:1  error  Dependency cycle via ./utils:2=>./mutation:1  import/no-cycle
Error:   2:1  error  Dependency cycle via ./utils:2=>./mutation:1  import/no-cycle
Error:   3:1  error  Dependency cycle via ./mutation:1             import/no-cycle
```

**Comment by benediktviebahn** [comment]
Oh right. Got it.

**Review by TkDodo — COMMENTED** [review]
I think this looks good! Two requests:
- can you please add tests for the `useIsMutating` hook as well
- I think we should also document `queryClient.isMutating` (next to [isFetching](https://react-query.tanstack.com/reference/QueryClient#queryclientisfetching))

**Comment by benediktviebahn** [comment]
Thanks for reviewing. Sure I will do that tomorrow.

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
I think this looks splendid! Let's wait for an additional review and then 🚀

**Review by tannerlinsley — APPROVED** [review]

**Pull request merged**
