### PR TITLE
refactor(devtools): move default theme to theme file, fix types

### PR DESCRIPTION
**Pull request by DamianOsipiuk**
Move the default theme to the proper file.
Fix types for `theme.tsx`
No functional changes.

### CODE REVIEW

**Comment by TkDodo** [comment]
have a look at the auto-deployed codesandboxes please - I can't see the devtools anymore :/

https://codesandbox.io/s/tannerlinsleyreact-query-basic-y5jg9

**Comment by DamianOsipiuk** [comment]
That is very weird, as it worked fine when I was checking locally.
I will double-check locally, and if I would not be able to find the issue, then maybe deployment to codesandbox somehow got broken.

**Comment by DamianOsipiuk** [comment]
@TkDodo Should be fixed now

**Pull request merged**
