### PR TITLE
feat(query): functions for refetchOn options

### PR DESCRIPTION
**Pull request by TkDodo**
refs #3110, #3517

### CODE REVIEW

**Comment by Noitidart** [comment]
Wow this feature is so great, I literally just needed this right now. As I have cacheTime at Infinity, and retry is also infinite. On unmount it goes into error state as retries are canceled. My refetchOnMount was false. So when came back, it would not refetch as its in error state. I need to make it refetch on mount only if its in error state. Thank you!!

**Comment by Noitidart** [comment]
> Wow this feature is so great, I literally just needed this right now. As I have cacheTime at Infinity, and retry is also infinite. On unmount it goes into error state as retries are canceled. My refetchOnMount was false. So when came back, it would not refetch as its in error state. I need to make it refetch on mount only if its in error state. Thank you!!


Oh man I just tested this, and it seems refetchOnMount is not being called while the query is in the `error` status.

**Comment by TkDodo** [comment]
@Noitidart i don't fully understand the problem. Can you open a discussion with a codesandbox reproduction please

**Comment by Noitidart** [comment]
Oh yes totally, thanks!

**Comment by Noitidart** [comment]
Oh man in codesandbox, when I unmount it, its not going into error state. I can't reproduce. Maybe because I just updated react-query thigns are cached.

Here's the codesandbox which is working fine - https://codesandbox.io/s/try-to-get-infinite-retry-to-error-55gf0l

1. Click button to mount it
2. We see in console "reading from disk" every 2 seconds
3. Click button to destroy it.
4. Wait 3 seconds, till the query throws.
5. Click button to mount it, and its still in loading state, weird. In my app when I click button to destroy it, it goes into error state, then on mount it stays in error state. But in the codesandbox on mount it always starts in loading state.

**Comment by Noitidart** [comment]
Ohhh it was the `retryOnMount` I had set that to false, man that's so silly I mixed it up with `refetchOnMount`. Man thanks man you're always helping out the newbies even though they're wasting your time. Man sorry about that. Awwwesome awwwwesome lib!

**Pull request merged**
