### PR TITLE
Add nextjs example

### PR DESCRIPTION
**Pull request by todortotev**
As discussed with @Ephem I'm going to add a Next.js example.

Just publishing that as a draft so we don't have multiple contributors working on it.

### CODE REVIEW

**Comment by Svish** [comment]
If I've understood correctly, `react-query` has been ported to Typescript (v3?), and Next.js is supposed to support Typescript as well... so... any chance of the example being in Typescript too? 🙏

**Comment by todortotev** [comment]
I think PR should be ready for review. If there is anything you want me to change, please let me know.
I have taken inspiration from the nextjs with-apollo example (layout related). As for the Typescript version, I don't mind making one if there is a demand for it.

**Comment by todortotev** [comment]
P.S. I totally forgot to add a codesandbox & edit the docs. Will do that tomorrow.

**Comment by todortotev** [comment]
Should be ready to merge.

**Comment by tannerlinsley** [comment]
Looks like there are some duplicate changes in here. Can you rebase with master or pull in the latest changes to eliminate them?

**Comment by todortotev** [comment]
> Looks like there are some duplicate changes in here. Can you rebase with master or pull in the latest changes to eliminate them?

Will do once I get back home!

**Pull request closed without merging**
