### PR TITLE
feat: add bi-directional infinite query support

### PR DESCRIPTION
**Pull request by boschni**
PR for discussion:

Adds ability to automatically support both directions:
```js
const {
  fetchNextPage,
  fetchPreviousPage,
  hasNextPage,
  hasPreviousPage,
  isFetchingNextPage,
  isFetchingPreviousPage
} = useInfiniteQuery(key, fn, {
  getNextPageParam: lastPage => lastPage.nextId,
  getPreviousPageParam: firstPage => firstPage.prevId
})

return (
  <>
    <button onClick={fetchPreviousPage} disabled={!hasPreviousPage || isFetchingPreviousPage}>Load previous</button>
     ...
    <button onClick={fetchNextPage} disabled={!hasNextPage || isFetchingNextPage}>Load next</button>
  </>
)
```

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I like it. Though, personally the append/prepend option is strange to think about. Technically this means that you can fetchNextPage(), but it would get prepended, correct? (and visa versa)

I realize that might be helpful for like... a news feed concept. But wouldn't that just end up being a visual reversal at render time and not at the data model?

**Comment by boschni** [comment]
Yeah the append mode is indeed for those kind of scenarios, where new pages appear at the top instead of at the bottom. Reversing the list when rendering would have the same effect. Mostly added it for convenience and because the reporter of https://github.com/tannerlinsley/react-query/issues/1086 was trying to load previous pages instead of reversing the list. Don’t have a strong opinion on this option though

**Comment by tannerlinsley** [comment]
The amount of code to support the option is tiny and it also won’t carry a lot of opinion with it into the future. So I think it’s fine.

**Comment by boschni** [comment]
This one should be ready. Also includes support for refetching when manual page params are provided

**Comment by tannerlinsley** [comment]
Excellent usage of the select option to avoid the reversal option.

**Pull request merged**
