### PR TITLE
Instruction for Kotlin/JS declarations

### PR DESCRIPTION
**Pull request by turansky**

### CODE REVIEW

**Comment by TkDodo** [comment]
Looking at the deploy preview (https://react-query-git-fork-turansky-patch-1-tannerlinsley.vercel.app/overview), I don't think the page is visible anywhere? I think you'd need to wire it to the menu or so, but I'm not sure it deserves it's own page ... ?

**Comment by turansky** [comment]
I have used [this page](https://github.com/tannerlinsley/react-table/blob/master/TYPESCRIPT.md) as example.
It also unavailable [on site](https://react-table.tanstack.com/)

**Comment by TkDodo** [comment]
Then it’s probably not a good source of inspiration 😅

**Comment by turansky** [comment]
@TkDodo You are right. New PR required

**Pull request closed without merging**
