### PR TITLE
chore(actions): add cache to NPM dependencies on GitHub actions

### PR DESCRIPTION
**Pull request by ruisaraiva19**
This uses [bahmutov/npm-install](https://github.com/bahmutov/npm-install) to install NPM dependencies with caching without any configuration.
Also uses [cycjimmy/semantic-release-action](https://github.com/cycjimmy/semantic-release-action) as a wrapper for [Semantic Release](https://github.com/semantic-release/semantic-release).

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Nice! Could you add this to react-table and react-charts, and react-virtual too? 😉

**Comment by ruisaraiva19** [comment]
> Nice! Could you add this to react-table and react-charts, and react-virtual too? 😉

Sure!

**Comment by ruisaraiva19** [comment]
@tannerlinsley one note regarding the `NPM_TOKEN` you have configured on the project.

The action is throwing the following error:
image

You can [follow this steps](https://docs.npmjs.com/about-two-factor-authentication#authorization-only) to fix the issue.

**Comment by tannerlinsley** [comment]
I haven’t changed anything And It was working before. You sure it’s Pulling from the right env variable?

Tanner Linsley

**Comment by ruisaraiva19** [comment]
> I haven’t changed anything And It was working before. You sure it’s Pulling from the right env variable? Tanner Linsley

I'm using the same variables you have before. I'm going to revert to the previously working semantic release step code. #895 895

**Comment by ruisaraiva19** [comment]
> Nice! Could you add this to react-table and react-charts, and react-virtual too? 😉

Here they are:
react-table: https://github.com/tannerlinsley/react-table/pull/2652
react-charts: https://github.com/tannerlinsley/react-charts/pull/115
react-virtual: https://github.com/tannerlinsley/react-virtual/pull/50

**Pull request merged**
