### PR TITLE
Update useQueries.md

### PR DESCRIPTION
**Pull request by Barna-Molnar**
useQueries does not accept an array or an object with options, you can add them as shown above, I think it should be in the doc

### CODE REVIEW

**Comment by TkDodo** [comment]
useQueries accepts an array _with_ query option objects - so the original sentence is perfectly fine. Also, we've changed the api of useQueries for v4, so the whole sentence is obsolete soon.

**Comment by Barna-Molnar** [comment]
If I try to add an array with options then I always get an error .... but if I try to add the options without an array then It works just fine, and I even get autocomplete for them. Do you have any idea why it behaves differently for me? I am using it with TS. By the way... What have you changed for v4? and when is the date of release?

**Comment by TkDodo** [comment]
I can't help you if you don't show the code. But please no screenshots. A codesandbox reproduction or a typescript playground!

changes for v4 are here: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-4
note that the useQuery api for v4 has changed!

**Comment by Barna-Molnar** [comment]
Yes, of course, I would not have done a screenshot, here is a ts playground [click here](https://playcode.io/898069) as you will see,  I can add any options without {} or [] as a ''list'' but with {} or [] I always get an error. Did I implement something wrong? Let me know pls if you need any info about it. Thank you

**Comment by TkDodo** [comment]
but, your code is alright the way it is?

The docs say:

> The `useQueries` hook accepts an array with query option objects identical to the `useQuery` hook.

and the useQuery hook can be called with:

```
useQuery({ queryKey: myKey, queryFn: myFn, staleTime: 0, refetchOnWindowFocus: true })
```

This is known as the object syntax for useQuery, and it's documented here: https://react-query.tanstack.com/guides/query-functions#using-a-query-object-instead-of-parameters

**Comment by Barna-Molnar** [comment]
Hi, yes it is working fine, 
So that it means, that I have not dug enough deep into the doc, but to be honest I could be a bit clearer or a simple example on that page in the doc, but you are right, and with your explanation I totally understand. The only thing was that we have not used the object syntax for useQuery and therefore It was strange for me. Again thx for your help now is everything clear.
Have a nice week

**Pull request closed without merging**
