### PR TITLE
fix: React implicit children type

### PR DESCRIPTION
**Pull request by maddhruv**
With this recent change in `@types/react` - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210 the type check fails for `QueryClientProvider` and other components which have `children` as a prop.

This is a particular failure when using `^@types/react@18`. Adding the `children` type explicitly to these components.

### CODE REVIEW

**Comment by maddhruv** [comment]
Closed since this is already being fixed here - https://github.com/tannerlinsley/react-query/pull/3482

**Comment by clothoo** [comment]
> Closed since this is already being fixed here - #3482

Is this a mistake? As in #3482, there's no change to `QueryClientProviderProps`

**Comment by clothoo** [comment]
My mistake. Reinstall the package the types got updated!

**Comment by TkDodo** [comment]
> Is this a mistake? As in https://github.com/tannerlinsley/react-query/pull/3482, there's no change to QueryClientProviderProps

Usage of React.FC was removed in an earlier PR for v4, so there was no change necessary

**Pull request closed without merging**
