### PR TITLE
fix(devtools): QueryKey height

### PR DESCRIPTION
**Pull request by always-maap**
fixes this

2022-04-12-122944_1920x1080_scrot

### CODE REVIEW

**Comment by always-maap** [comment]
oh my bad. it fixes the height. I thought this is not right. if it is feel free to close <3

2022-04-12-142351_1920x1080_scrot

**Comment by TkDodo** [comment]
thanks, I don't think its per design. However, in the preview build (https://codesandbox.io/s/tannerlinsley-react-query-basic-forked-ko2pop?file=/src/index.js), I can still see the issue being present.

Screenshot 2022-04-15 at 19 47 23

the container uses `align-items: stretch`, and if we'd change that to `flex-start`, the issue would go away for me...

https://github.com/tannerlinsley/react-query/blob/c1ae82ba188fd5abda5e256cac070145e5941447/src/devtools/devtools.tsx#L710

**Comment by always-maap** [comment]
I revert the height and fix the container `alignItems`. please squash and merge if you consider merging this. if it's unnecessary feel free to close it <3

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
