### PR TITLE
RFC - define query types

### PR DESCRIPTION
**Pull request by JakeGinnivan**
This is just an idea so haven't taken it very far. 

## The goal

To allow you to define the available keys and data types once and be enforced throughout the API

## Example

By putting this type in your code:

```
declare module 'react-query' {
  export interface QueryTypes {
    'typed-todo': TodoItem
  }
}
```

useQuery is now typed and the return type is enforced.

image

image

## Current issues

I have not yet figured out how to keep compatibility, the current approach will require the user to either define their types, or opt into the existing behavior by adding the following to their code.

```
declare module 'react-query' {
  export interface QueryTypes extends Record<string, any>
}
```

And also going through the entire public API to use the QueryTypes, we could use it to type the cache functions too

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This is a cool idea. I don't use types a lot, so this would just need to be vetted by a bunch of people that we trust and a decision made. 👍

**Comment by JakeGinnivan** [comment]
What is the best way to make that happen?

Jump into discord or could you tag a few people here?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tannerlinsley** [comment]
Woah... I legit don't remember closing this. We should reopen it.

**Comment by tannerlinsley** [comment]
And yes, let's tag a few people here.

**Comment by tannerlinsley** [comment]
I think another way (if my TS knowledge is sufficient) is that you could maybe define your own query type for `useQuery` that extends the original useQueryType, but with a specific key? That way you could reference that query type in your code instead of the generic one. I realize that doesn't restrict people from using the open-ended useQuery though. Does that sound remotely right?

**Pull request closed without merging**
