### PR TITLE
Deduplicate packages in yarn.lock

### PR DESCRIPTION
**Pull request by Naoya9922**
Deduplicated packages in yarn.lock ~~to reduce bundle size~~.

```bash
$ npx yarn-deduplicate --strategy highest
```

### CODE REVIEW

**Comment by TkDodo** [comment]
How would this affect bundle size?

**Comment by Naoya9922** [comment]
> How would this affect bundle size?

As it will depend fewer libraries after deduplicating.

**Comment by TkDodo** [comment]
> As it will depend fewer libraries after deduplicating.

but, we don't have runtime dependencies - only devDependencies 🤔

**Comment by Naoya9922** [comment]
Oh, I got it.
It won't affect bundle size as you say.
It will just eliminating duplicated devDependencies.

**Comment by Naoya9922** [comment]
Should PR be closed?

**Pull request closed without merging**
