### PR TITLE
Add types to react-query package

### PR DESCRIPTION
**Pull request by nksaraf**
Hi, thanks for this awesome library. I was using it with typescript but found that the typings at `@types/react-query` are old and not up to date with the API. So I refreshed them and thought it would be a good idea if the library shipped with them. 

P.S: Just starting with contributing to OSS, if I missed any steps in this process, please correct me

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Hey, this is great! I'm stoked that you're getting into contributing :)

So in the case of these types (which are awesome), for the time being we don't host the types directly here in this repo since the library isn't written in TS itself. However, @types/react-query could definitely use this update:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-query/index.d.ts

**Comment by jarleriksen** [comment]
Hi @nksaraf - Awesome types! Are you going to create a pull request on the DefinitelyTyped repo? :)

**Comment by nksaraf** [comment]
Hi @jarleriksen I want to do that. But like I said, I am new to this and contributing to DefinitelyTyped seemed a little daunting to me. I don't want to screw things up there. Any help/guidance will be amazing. I have been using the typings internally for my project but haven't got time to do all the things necessary for that repo. If you could use the typings internally, it would be give me some confidence to make the effort for the PR. Also I only use the useQuery and useMutation hooks mainly, not sure if everything is definitely correct. But here is a link to a gist https://gist.github.com/nksaraf/a00f0670c1d29e9490a1d1d856a3866d with the types file only (updated with some bug fixes against this PR)

**Comment by tannerlinsley** [comment]
FYI, you're cordially invited to this discussion: https://github.com/tannerlinsley/react-query/discussions/362

**Pull request closed without merging**
