### PR TITLE
fix: useSyncExternalStore re-export

### LINKED ISSUE #3637: react-query v4: useSyncExternalStore error with Create React App
### Describe the bug

Using `react-scripts@4.0.3` (a.k.a. [Create React App](https://create-react-app.dev)) does not work with `react-query@4.0.0-beta.X`. The following is the error that occurs when running the development server:

```
./node_modules/react-query/lib/reactjs/useSyncExternalStore.mjs
Can't reexport the named export 'useSyncExternalStore' from non EcmaScript module (only default export is available)
```

### Your minimal, reproducible example

https://github.com/tmm/react-query-debug

### Steps to reproduce

1. Clone repo
2. Install dependencies `npm i`
3. Run development server `npm start`

### Expected behavior

I expected to not get an `useSyncExternalStore` error

### How often does this bug happen?

Every time

### Screenshots or Videos

image

### Platform

- OS: macOS
- Browser: Firefox, Chrome

### react-query version

4.0.0-beta.X

### TypeScript version

_No response_

### Additional context

Reporting based on [this comment](https://github.com/tmm/wagmi/issues/398#issuecomment-1115003119) by **TkDodo** for https://github.com/tmm/wagmi/issues/398

### PR DESCRIPTION
**Pull request by TkDodo**
fixes #3637

### CODE REVIEW

**Review by sachinraja — APPROVED** [review]
I would recommend testing this to make sure, but changes look good to me

**Comment by TkDodo** [comment]
thx. I tested it manually on the example repo from the issue by using the codesandbox preview build, and it worked. not sure how to automate it though.

**Comment by sachinraja** [comment]
For now it would help to upgrade code sandbox to the latest version of CRA.

**Pull request merged**
