### PR TITLE
docs: fix suspense example

### PR DESCRIPTION
**Pull request by nikasepiskveradze**
This is the possible fix for #3453

### CODE REVIEW

**Review by TkDodo — COMMENTED** [review]
wouldn't the peerDependency installation fail, because react-query v3 still requires a peerDependency of react 16 || 17 ?

**Comment by TkDodo** [comment]
i tried it out and it seems to work. however, the interface of `useTransition` seems to have changed.

We do:

```
const [startTransition, isPending] = React.useTransition({
```

it should be:

```
const [isPending, startTransition] = React.useTransition({
```

**Comment by nikasepiskveradze** [comment]
> wouldn't the peerDependency installation fail, because react-query v3 still requires a peerDependency of react 16 || 17 ?

Agree, I don't have other solution so we can close this merge request

**Comment by TkDodo** [comment]
we can rebase this pr to `alpha` once I have merged:
- #3064

**Comment by TkDodo** [comment]
beta is released with react 18 support. can you rebase this PR onto the `beta` branch please, then we can go ahead with merging :)

**Comment by nikasepiskveradze** [comment]
> beta is released with react 18 support. can you rebase this PR onto the `beta` branch please, then we can go ahead with merging :)

I'm not sure if i did it correctly, If something is wrong I will create new branch from "beta" and send PR of those changes

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
