### PR TITLE
fix(core): remove enabled condition in queryObserver

### LINKED ISSUE #2434: Infinate querying when query fails and using suspense + enabled flag
**Describe the bug**
Using suspense + enabled flag to delay querying, when a query fails will cause infinite querying.

**To Reproduce**

Core code:
```ts
function query() {
  return new Promise((resolve, reject) => {
    console.count("query");
    setTimeout(() => reject("Query Error"), 1000);
  });
}

function DataFetch() {
  const [enabled, setEnabledStatus] = useState(false);
  useQuery("mock", query, { suspense: true, enabled, retry: 0 });

  return <button onClick={() => setEnabledStatus(true)}>Start</button>;
}
```

Complete code: https://codesandbox.io/s/react-query-bug-suspense-enabled-flag-2w762?file=/src/App.tsx

1. Click the `Start` Button
2. Look at `Console`, you will see many queries.

**Expected behavior**
Throw Error and only query once.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 91.0.4472.114

**Additional context**
After removing the `enabled` or `suspense` flag, anything works well.

### PR DESCRIPTION
**Pull request by JaeYeopHan**
closes #2434

(would a description be enough as an issue link?)

### CODE REVIEW

**Review by TkDodo — CHANGES_REQUESTED** [review]
please add the test from the issue, thanks.

**Comment by JaeYeopHan** [comment]
> please add the test from the issue, thanks.

OMG, every changes are not committed!! sorry...

**Comment by JaeYeopHan** [comment]
node 14...? 🥲

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
